# The format version is an indicator of the compatibility of third-party exercises with the
# Rustlings program.
# The format version is not the same as the version of the Rustlings program.
# In case Rustlings makes an unavoidable breaking change to the expected format of third-party
# exercises, you would need to raise this version and adapt to the new format.
# Otherwise, the newest version of the Rustlings program won't be able to run these exercises.
format_version = 1

# Optional multi-line message to be shown to users when just starting with the exercises.
welcome_message = """Rustlings-jp(サードパーティー)へようこそ！ 一緒にRustについて学んでいきましょう！！！"""

# Optional multi-line message to be shown to users after finishing all exercises.
final_message = """お疲れ様でした！:D"""

# Repeat this section for every exercise.
[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "intro1"
dir = "00_intro"
test = false
hint = """???"""
skip_check_unsolved = true

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "intro2"
dir = "00_intro"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables1"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables2"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables3"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables4"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables5"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "variables6"
dir = "01_variables"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "functions1"
dir = "02_functions"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "functions2"
dir = "02_functions"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "functions3"
dir = "02_functions"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "functions4"
dir = "02_functions"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "functions5"
dir = "02_functions"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "if1"
dir = "03_if"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "if2"
dir = "03_if"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "if3"
dir = "03_if"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "quiz1"
dir = "quizzes"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types1"
dir = "04_primitive_types"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types2"
dir = "04_primitive_types"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types3"
dir = "04_primitive_types"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types4"
dir = "04_primitive_types"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types5"
dir = "04_primitive_types"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "primitive_types6"
dir = "04_primitive_types"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "vecs1"
dir = "05_vecs"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "vecs2"
dir = "05_vecs"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "move_semantics1"
dir = "06_move_semantics"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "move_semantics2"
dir = "06_move_semantics"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "move_semantics3"
dir = "06_move_semantics"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "move_semantics4"
dir = "06_move_semantics"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "move_semantics5"
dir = "06_move_semantics"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "structs1"
dir = "07_structs"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "structs2"
dir = "07_structs"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "structs3"
dir = "07_structs"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "enums1"
dir = "08_enums"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "enums2"
dir = "08_enums"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "enums3"
dir = "08_enums"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "strings1"
dir = "09_strings"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "strings2"
dir = "09_strings"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "strings3"
dir = "09_strings"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "strings4"
dir = "09_strings"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "modules1"
dir = "10_modules"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "modules2"
dir = "10_modules"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "modules3"
dir = "10_modules"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "hashmaps1"
dir = "11_hashmaps"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "hashmaps2"
dir = "11_hashmaps"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "hashmaps3"
dir = "11_hashmaps"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "quiz2"
dir = "quizzes"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "options1"
dir = "12_options"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "options2"
dir = "12_options"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "options3"
dir = "12_options"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors1"
dir = "13_error_handling"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors2"
dir = "13_error_handling"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors3"
dir = "13_error_handling"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors4"
dir = "13_error_handling"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors5"
dir = "13_error_handling"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "errors6"
dir = "13_error_handling"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "generics1"
dir = "14_generics"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "generics2"
dir = "14_generics"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "traits1"
dir = "15_traits"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "traits2"
dir = "15_traits"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "traits3"
dir = "15_traits"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "traits4"
dir = "15_traits"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "traits5"
dir = "15_traits"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "quiz3"
dir = "quizzes"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "lifetimes1"
dir = "16_lifetimes"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "lifetimes2"
dir = "16_lifetimes"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "lifetimes3"
dir = "16_lifetimes"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "tests1"
dir = "17_tests"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "tests2"
dir = "17_tests"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "tests3"
dir = "17_tests"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "iterators1"
dir = "18_iterators"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "iterators2"
dir = "18_iterators"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "iterators3"
dir = "18_iterators"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "iterators4"
dir = "18_iterators"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "iterators5"
dir = "18_iterators"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "box1"
dir = "19_smart_pointers"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "rc1"
dir = "19_smart_pointers"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "arc1"
dir = "19_smart_pointers"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "cow1"
dir = "19_smart_pointers"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "threads1"
dir = "20_threads"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "threads2"
dir = "20_threads"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "threads3"
dir = "20_threads"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "macros1"
dir = "21_macros"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "macros2"
dir = "21_macros"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "macros3"
dir = "21_macros"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "macros4"
dir = "21_macros"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "clippy1"
dir = "22_clippy"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "clippy2"
dir = "22_clippy"
test = false
hint = """???"""
skip_check_unsolved = true

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "clippy3"
dir = "22_clippy"
test = false
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "using_as"
dir = "23_conversions"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "from_into"
dir = "23_conversions"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "from_str"
dir = "23_conversions"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "try_from_into"
dir = "23_conversions"
hint = """???"""

[[exercises]]
# Exercise name which is the exercise file name without the `.rs` extension.
name = "as_ref_mut"
dir = "23_conversions"
hint = """???"""
